### ISSUE TITLE
Crashing when "transforming" loading Sponza resource. Clicked on gear on bottom left of asset that is imported.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#246] opened 2020-05-23 09:26 UTC
Crashes in DocumentTasks.cpp line 23 in function Execute..

It looks like m_document is being freed before calling Execute.

Source of problem is that in MeshImportUtils.cpp line 328. WaitForPendingTasks is causing an Async save. But the Document has already been saved and closed.

Callstack.
 	vcruntime140d.dll!00007ffe2d141392()	Unknown
 	ezFoundation.dll!ezDynamicArrayBase<char>::operator=(ezDynamicArrayBase<char> && rhs) Line 96	C++
 	ezFoundation.dll!ezDynamicArray<char,ezDefaultAllocatorWrapper>::operator=(ezDynamicArray<char,ezDefaultAllocatorWrapper> && rhs) Line 300	C++
 	ezFoundation.dll!ezHybridArray<char,32,ezDefaultAllocatorWrapper>::operator=(ezHybridArray<char,32,ezDefaultAllocatorWrapper> && rhs) Line 52	C++
 	ezFoundation.dll!ezHybridStringBase<32>::operator=(ezHybridStringBase<32> && rhs) Line 119	C++
 	[External Code]	
>	ezToolsFoundation.dll!ezSaveDocumentTask::Execute() Line 23	C++
 	ezFoundation.dll!ezTask::Run(unsigned int uiInvocation) Line 55	C++
 	ezFoundation.dll!ezTaskSystem::ExecuteTask(ezTaskPriority::Enum FirstPriority, ezTaskPriority::Enum LastPriority, bool bOnlyTasksThatNeverWait, const ezTaskGroupID & WaitingForGroup, ezAtomicInteger<int> * pWorkerState) Line 125	C++
 	ezFoundation.dll!ezTaskWorkerThread::Run() Line 67	C++
 	ezFoundation.dll!RunThread(ezThread * pThread) Line 49	C++
 	ezFoundation.dll!ezThreadClassEntryPoint(void * lpThreadParameter) Line 15	C++
 	[External Code]	

Windows 10
Master Branch.

Commit hash:	e4d783469d6a3798e6bb91670f2163e959f37a2b
Parent:			5bc6718511

**Comment by jankrassnigg** [comment] 2020-05-23 20:42
Thanks for the report. I guess that this is a duplicate of #209, or at least related, but we'll keep this ticket open for now to verify. It might be something else after all.

**Closed as completed** 2020-05-25 21:09 UTC
