### ISSUE TITLE
After importing an Animated Mesh and Skeleton as FBX from Mixamo and assigning a Skeleton to the Animated Mesh, I was unable to see the Mesh in the editor. 

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#930] opened 2023-05-01 18:50 UTC
After importing an Animated Mesh and Skeleton as FBX from Mixamo and assigning a Skeleton to the Animated Mesh and transforming the Animated Mesh asset, I was unable to see the Mesh in the editor.
If I restart the editor the Mesh shows up just fine. I am not sure why the mesh is not updated after being transformed.

Commit hash.
fb2679e780435a28192bbc390adba82971a64a87
"Prefabs may now attach components to their parent instance node (#927)"

**Comment by jankrassnigg** [comment] 2023-05-01 18:53
Duplicate of #631.

**Closed as completed by jankrassnigg** 2023-05-01 18:53 UTC

**Comment by antonyjones67** [comment] 2023-05-01 19:10
Cool. Thank you.
