### ISSUE TITLE
Asset filesystem watcher only works for the first change

### ISSUE THREAD

**Issue by C-Core** [ezEngine/ezEngine#178] opened 2020-03-26 09:30 UTC
If you have e.g. a texture or a mesh and change the source file on disk the Editor only detects the first change. If you change the same source file again the changes are not detected anymore. You can press the check filesystem button in the asset browser and then the asset is marked as modified. So I guess there is something broken with the filesystem watcher.

**Comment by C-Core** [comment] 2020-03-26 09:34
Might depend on the tool you use to change the source file. I used Blender's fbx export for meshes and Substance Designer for textures.

**Comment by Sanakan8472** [comment] 2020-04-22 12:14
Fixed in pull request #197 from ezEngine/user/cm/assetCurator_fixes

**Comment by C-Core** [comment] 2020-05-05 11:36
Still doesn't work for some files, especially big ones.

**Comment by jankrassnigg** [comment] 2022-08-18 20:48
@C-Core @Ingrater did recent changes have an effect on this?

**Comment by Ingrater** [comment] 2022-08-18 20:57
Yes, I actually tried to reproduce this issue after my recent changes to the file watcher. I could not reproduce this issue. I'll mark this issue as fixed. @C-Core please re-open in case you run into it again.

**Closed** 2022-08-18 20:57 UTC
Labels: bug
