### ISSUE TITLE
[BUG]Editor freezes when trying to transform an animated mesh

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#351] opened 2020-12-19 13:37 UTC
**Bug description:**
The editor becomes indefinitely unresponsive when trying to transform an animated mesh asset.

The issue seems to resolve itself on subsequent attempts.

**How to Reproduce:**
1. Create an animated mesh asset.
2. Reference the mesh and skeleton.
3. Leave other options as default.
4. Hit the transform button

**Screenshots:**
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/78807/102690725-5a138400-41d5-11eb-83ff-f48da66a54eb.png)

**Dev-branch commit hash:**
618164c8b233a6f4e7b5145f766f9448504a223e

**Comment by jankrassnigg** [comment] 2021-06-03 11:51
Can you still reproduce this? There were several bug fixes around mesh import and I haven't encountered this anymore recently.

**Comment by jankrassnigg** [comment] 2021-07-11 09:43
Closing this now, since I haven't observed it in a long while.

**Closed as completed by jankrassnigg** 2021-07-11 09:43 UTC
Labels: cannot reproduce
