### ISSUE TITLE
[FEATURE] Create Prefab on import

### ISSUE THREAD

**Issue by PlasmaDev5** [ezEngine/ezEngine#1206] opened 2024-02-13 19:47 UTC
When importing a render mesh and physics it would vastly improve development time to auto create prefabs with the mesh and physics. This in future could also include mesh splitting for multi-mesh files.

**Comment by jankrassnigg** [comment] 2024-02-17 12:58
Duplicate of https://github.com/ezEngine/ezEngine/issues/887

**Closed as completed by jankrassnigg** 2024-02-17 12:58 UTC
Labels: duplicate
